# Generated by Django 2.2.3 on 2019-07-17 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_posted', models.DateField(auto_now=True)),
                ('event_date', models.DateTimeField()),
                ('organizer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeatType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bbqplanner.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('guest_count', models.IntegerField(default=0)),
                ('event', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bbqplanner.Event')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorMeatChoice',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('meat', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bbqplanner.MeatType')),
                ('visitor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bbqplanner.Visitor')),
            ],
        ),
    ]
